gayeong/Match_up/Match_up/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls', namespace = "account")),
    path('', include('community.urls', namespace = "community")),
    path('', include('teampage.urls', namespace = "teampage")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gayeong/Match_up/account/urls.py
from django.contrib import admin
from django.urls import path, include 

from.import views

app_name = "account"

urlpatterns = [
    path('', views.main, name = 'main'),
    path('log_in/', views.log_in, name = "log_in"),
    path('log_out/', views.log_out, name = "log_out"),
    path('sign_up/', views.sign_up, name = "sign_up"),
    path('my_page/', views.my_page, name = "my_page"),
]

gayeong/Match_up/community/urls.py
from django.contrib import admin
from django.urls import path, include 

from.import views

app_name = "community"

urlpatterns = [
    path('free_board/', views.free_board, name = 'free_board'),
    path('review_board/', views.review_board, name = "review_board"),
    path('hire_board/', views.hire_board, name = "hire_board"),
    path('createPost_free/', views.createPost_free, name = "createPost_free"),
    path('createPost_review/', views.createPost_review, name = "createPost_review"),
    path('createPost_hire/', views.createPost_hire, name = "createPost_hire"),
    
    path('turnBack/<int:id>/', views.turnBack, name = "turnBack"),
    path('postDetail/<int:id>/', views.postDetail, name = "postDetail"),
    path('postDelete/<int:id>/', views.postDelete, name = "postDelete"),
    path('postEdit/<int:id>/', views.postEdit, name = "postEdit"),

    #path('turnBack/', views.turnBack, name = "turnBack"),
]

gayeong/Match_up/community/models.py
from django.db import models
from django.conf import settings
from account.models import *



# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=50, help_text="블로그 글의 분류를 입력하세요.")
    num_hit = models.PositiveIntegerField(default = 0)
    

    def __str__(self):
        return self.name

class TimeDate(models.Model):
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    class Meta:
        abstract = True

class Community_Post(TimeDate):
    author = models.ForeignKey(Profile, on_delete=models.CASCADE) # 작성자
    title = models.CharField(max_length=200)
    title_image = models.ImageField(upload_to = 'image', blank=True)
    content = models.TextField()
    #하나의 글을 여러가지의 분류에 해당될 수 있다.(ex:정보, 유머), 하나의 분류에는 여러가지 글이 포함될 수 있죠.(정보 카테고리에 글 10개)
    category = models.ManyToManyField(Category, help_text="글의 분류를 설정하세요.")

    def __str__(self):
        return self.title

    #1번 글의 경우 -> post/1
    def get_absolute_url(self):
        return reverse("post", args=[str(self.id)]).py

    def is_title_more11(self):
        return len(self.title) > 11
    
    def get_title_under11(self):
        return self.title[:11]




    

gayeong/Match_up/community/forms.py
from django import forms
from .models import *
from django.forms.widgets import ClearableFileInput

class Community_Form(forms.ModelForm):
    class Meta:
        model = Community_Post
        fields = ('title', 'title_image', 'content')
        labels = {
            'title': '',
            'title_image': '',
            'content': '',
        }
        

gayeong/Match_up/community/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import auth
from account.models import *
from .models import *
from .forms import *

# Create your views here.

def free_board(request):
    categorys = Category.objects.filter(name = "자유게시판")
    post = Community_Post.objects.filter(category__name = "자유게시판").order_by('-created_at')
    context = {
        'post':post,
        'categorys' : categorys,
    }
    return render(request, 'free_board.html', context)

def review_board(request):
    categorys = Category.objects.filter(name = "경기 후기")
    post = Community_Post.objects.filter(category__name = "경기 후기").order_by('-created_at')
    context = {
        'post':post,
        'categorys' : categorys,
    }
    return render(request, 'review_board.html', context)


def hire_board(request):
    categorys = Category.objects.filter(name = "용병 모집")
    post = Community_Post.objects.filter(category__name =  "용병 모집").order_by('-created_at')
    context = {
        'post':post,
        'categorys' : categorys,
    }
    return render(request, 'hire_board.html', context)

def createPost_free(request):
    if request.method == "POST":
        form = Community_Form(request.POST)
        print("dkdkd")
        if form.is_valid():

            username = request.user.username
            my_profile = Profile.objects.get(user__username=request.user)

            community_post = form.save(commit=False)
            community_post.author = my_profile
            cat = Category.objects.get(name = "자유게시판")
            community_post.save()
            
            community_post.category.add(cat) # 자유게시판 id값 5
            
            #author = Profile.objects.get(user__username=request.user)
            # authod_id = request.session.get('user')
            # user = Users.objects.get(pk = authod_id)
            community_post.save()

            # new_Post = Community_Post(
            #     # title = form.cleaned_data['title'],
            #     # title_image = form.cleaned_data['title_image'],
            #     # content = form.cleaned_data['content'],
            #     author = my_profile,
            #     category = get_object_or_404(Category,pk = 1),
            # )
            return redirect('/free_board')

    else:
        print("통과 불가능")
        form = Community_Form()
        context = {
            'form' : form,
        }
        return render(request, 'createPost_free.html', context)

def createPost_review(request):
    if request.method == "POST":
        form = Community_Form(request.POST)
        if form.is_valid():

            username = request.user.username
            my_profile = Profile.objects.get(user__username=request.user)

            community_post = form.save(commit=False)
            community_post.author = my_profile
            cat = Category.objects.get(name = "경기 후기")
            community_post.save()
            
            community_post.category.add(cat) # 자유게시판 id값 5
            
            #author = Profile.objects.get(user__username=request.user)
            # authod_id = request.session.get('user')
            # user = Users.objects.get(pk = authod_id)
            community_post.save()

            # new_Post = Community_Post(
            #     # title = form.cleaned_data['title'],
            #     # title_image = form.cleaned_data['title_image'],
            #     # content = form.cleaned_data['content'],
            #     author = my_profile,
            #     category = get_object_or_404(Category,pk = 1),
            # )
            return redirect('/review_board')

    else:
        form = Community_Form()
        context = {
            'form' : form,
        }
        return render(request, 'createPost_review.html', context)

def createPost_hire(request):
    if request.method == "POST":
        form = Community_Form(request.POST)
        if form.is_valid():

            username = request.user.username
            my_profile = Profile.objects.get(user__username=request.user)

            community_post = form.save(commit=False)
            community_post.author = my_profile
            cat = Category.objects.get(name = "용병 모집")
            community_post.save()
            
            community_post.category.add(cat) # 자유게시판 id값 5
            
            #author = Profile.objects.get(user__username=request.user)
            # authod_id = request.session.get('user')
            # user = Users.objects.get(pk = authod_id)
            community_post.save()

            # new_Post = Community_Post(
            #     # title = form.cleaned_data['title'],
            #     # title_image = form.cleaned_data['title_image'],
            #     # content = form.cleaned_data['content'],
            #     author = my_profile,
            #     category = get_object_or_404(Category,pk = 1),
            # )
            return redirect('/hire_board')

    else:
        form = Community_Form()
        context = {
            'form' : form,
        }
        return render(request, 'createPost_hire.html', context)

def turnBack(request, id):
    post = Community_Post.objects.get(pk = id)
    cat = post.category.related_val
    print(cat)
    if(cat == (1,)):
        return redirect('/free_board')

    elif(cat == (2,)):
        return redirect('/review_board')

    elif(cat == (3,)):
        return redirect('/hire_board')
    else:

        return redirect("/")

    
def postDetail(request, id):
    post = get_object_or_404(Community_Post, pk = id)
    context = {
        'post' : post,
    }
    return render(request, 'postDetail.html', context)

def postDelete(request, id):
    post = get_object_or_404(Community_Post, pk=id)
    post.delete()
    return redirect("/free_board")

def postEdit(request, id):
    post = get_object_or_404(Community_Post, pk = id)
    context = {
        'post': post,
        'dform' : Community_Form(instance = Community_Post),
    }

    return render(request, 'postEdit.html', context)

def postUpdate(request, id):
    post = get_object_or_404(Community_Post, pk = id)
    dform = Community_Form(request.POST, instance = Community_Post)
    if dform.is_valid():
        dform.save()
    return redirect('/postDtail/'+id)

gayeong/Match_up/community/templates/createPost_free.html
{% extends 'base.html' %}

{% block title %}Create Post{% endblock %}

{% block sty %} 

{% endblock %}

{% block content %} 

<div class = "container" style="position:relative">
  <form action = "{% url 'community:createPost_free' %}" method = "post">
    {% csrf_token %}
    {{form.title}}
    {{form.title_image}}
    {{form.content}}

    <input type = "submit" value = "글쓰기" >
    <!-- <a class="btn btn-primary" href = "{% url 'community:createPost_free' %}" role="button" style = "float: right; margin-top: 0.3rem; margin-bottom:1rem;">글쓰기</a> -->
    <!-- href = "{% url 'community:createPost_free' %}" -->
  </form>
</div>

  


{% endblock %}

gayeong/Match_up/community/templates/createPost_hire.html
{% extends 'base.html' %}

{% block title %}Create Post{% endblock %}

{% block sty %} 

{% endblock %}

{% block content %} 


<div class = "container" style="position:relative">
  <form action = "{% url 'community:createPost_hire' %}" method = "post">
    {% csrf_token %}
    {{form.title}}
    {{form.title_image}}
    {{form.content}}

    <input type = "submit" value = "글쓰기" >
    <!-- <a class="btn btn-primary" href = "{% url 'community:createPost_free' %}" role="button" style = "float: right; margin-top: 0.3rem; margin-bottom:1rem;">글쓰기</a> -->
    <!-- href = "{% url 'community:createPost_free' %}" -->
  </form>
</div>

  


{% endblock %}

gayeong/Match_up/community/templates/createPost_review.html
{% extends 'base.html' %}

{% block title %}Create Post{% endblock %}

{% block sty %} 

{% endblock %}

{% block content %} 


<div class = "container" style="position:relative">
  <form action = "{% url 'community:createPost_review' %}" method = "post">
    {% csrf_token %}
    {{form.title}}
    {{form.title_image}}
    {{form.content}}

    <input type = "submit" value = "글쓰기" >
    <!-- <a class="btn btn-primary" href = "{% url 'community:createPost_free' %}" role="button" style = "float: right; margin-top: 0.3rem; margin-bottom:1rem;">글쓰기</a> -->
    <!-- href = "{% url 'community:createPost_free' %}" -->
  </form>
</div>

  


{% endblock %}

gayeong/Match_up/community/templates/free_board.html
{% extends 'communitylayout/post_view.html' %}

{% block title %}free_board{% endblock %}

{% block write %}

    {% if user.is_authenticated %}
    <form action = "" method = "GET">
    <div class="container-fluid">
        <a class="btn btn-primary" href="{% url 'community:createPost_free' %}" role="button" style = "float: right; margin-top: 0.3rem; margin-bottom:1rem;">글쓰기</a>
    </div>
    </form>
    {% endif %}

{% endblock %}

gayeong/Match_up/community/templates/hire_board.html
{% extends 'communitylayout/post_view.html' %}

{% block title %}hire_board{% endblock %}

{% block write %}
    
    {% if user.is_authenticated %}
    <form action = "" method = "GET">
    <div class="container-fluid">
        <a class="btn btn-primary" href="{% url 'community:createPost_hire'%}" role="button" style = "float: right; margin-top: 0.3rem; margin-bottom:1rem;">글쓰기</a>
    </div>
    </form>
    {% endif %}

{% endblock %}

gayeong/Match_up/community/templates/postDetail.html
{% extends 'base.html' %}

{% block title %}Detail Post{% endblock %}

{% block sty %} 

{% endblock %}

{% block content %} 

<div class = "led">
    <h3>{% for name in post.category.all %}{{ name }}{% endfor %}</h3>
</div>

<div class = container style="position:relative">
    <div>
        <span></span><h2><a class="btn btn-outline-secondary" href="{% url 'community:turnBack'  post.id %}">뒤로가기</a> </h2>
    </div>
    <div class="col-md-5 p-lg-5 mx-auto my-5">
        <h2 style = "text-align: center;"><a href="#" class="badge badge-success">작성자 : {{post.author.user_name}}</a></h2>
        <h5 style = "text-align: center; font-size:x-large" class="display-4 font-weight-normal">title : {{post.title}}</h4><br>
        <p style = "text-align: center;"class="lead font-weight-normal">{{post.content}}</p>
        <p style = "text-align: center;" ><img>{{post.title_image}}</p>
        <br>
        <h5 style = "text-align: center; font-size: medium" class="display-4 font-weight-normal">생성일 : {{post.created_at}}</h5>
        <h5 style = "text-align: center; font-size: medium" class="display-4 font-weight-normal">업데이트일 : {{post.updated_at}}</h5><br>

        <div style = "float: right;">
            <a href="#" style = "font-size: medium;" class="badge badge-warning">수정하기</a> <span></span> <a style = "font-size: medium;" href="#" class="badge badge-danger"data-toggle="modal" data-target="#exampleModal">삭제하기</a>
        </div>

        <!-- 삭제용 modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">삭제하시겠습니까?</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-footer">
                 <button type="button" class="btn btn-secondary" data-dismiss="modal">닫기</button>
                 <button type="button" class="btn btn-danger"><a href = "{% url 'community:postDelete' post.id %}">삭제</a></button>
                </div>
              </div>
            </div>
          </div>

    </div>
</div>

  


{% endblock %}

gayeong/Match_up/community/templates/postEdit.html
{% extends 'base.html' %}

{% block title %}Detail Post{% endblock %}

{% block sty %} 

{% endblock %}

{% block content %}

<form action = "{% url 'community:postUpdate' post.id %}" method = "POST">
 {% csrf_token %}
 {{dform.title}}
 <input type = "submit" value = "수정">
</form>

{% endblock %}

gayeong/Match_up/community/templates/review_board.html
{% extends 'communitylayout/post_view.html' %}

{% block title %}Review_Board{% endblock %}

{% block write %}

    {% if user.is_authenticated %}
    <form action = "" method = "GET">
    <div class="container-fluid">
        <a class="btn btn-primary" href="{% url 'community:createPost_review' %}" role="button" style = "float: right; margin-top: 0.3rem; margin-bottom:1rem;">글쓰기</a>
    </div>
    </form>
    {% endif %}

{% endblock %}