gayeong/Match_up/Match_up/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls', namespace = "account")),
    path('', include('community.urls', namespace = "community")),
    path('', include('teampage.urls', namespace = "teampage")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gayeong/Match_up/account/urls.py
from django.contrib import admin
from django.urls import path, include 

from.import views

app_name = "account"

urlpatterns = [
    path('', views.main, name = 'main'),
    path('log_in/', views.log_in, name = "log_in"),
    path('log_out/', views.log_out, name = "log_out"),
    path('sign_up/', views.sign_up, name = "sign_up"),
    path('my_page/', views.my_page, name = "my_page"),
]

gayeong/Match_up/community/urls.py
from django.contrib import admin
from django.urls import path, include 

from.import views

app_name = "community"

urlpatterns = [
    path('free_board/', views.free_board, name = 'free_board'),
    path('review_board/', views.review_board, name = "review_board"),
    path('hire_board/', views.hire_board, name = "hire_board"),
    path('createPost_free/', views.createPost_free, name = "createPost_free"),
    path('createPost_review/', views.createPost_review, name = "createPost_review"),
    path('createPost_hire/', views.createPost_hire, name = "createPost_hire"),
    
    path('turnBack/<int:id>/', views.turnBack, name = "turnBack"),
    path('postDetail/<int:id>/', views.postDetail, name = "postDetail"),
    path('postDelete/<int:id>/', views.postDelete, name = "postDelete"),
    path('postEdit/<int:id>/', views.postEdit, name = "postEdit"),

    #path('turnBack/', views.turnBack, name = "turnBack"),
]

gayeong/Match_up/teampage/urls.py
from django.contrib import admin
from django.urls import path, include 

from.import views

app_name = "teampage"

urlpatterns = [
    path('management/', views.management, name = 'management'),
    path('teaminfo/', views.teaminfo, name = "teaminfo"),
    path('testpage/', views.testpage, name = "testpage"),
    path('simulation/', views.simulation, name = "simulation"),
    path('team_list/', views.team_list, name = "team_list"),
    path('team_create/', views.team_create, name = "team_create"),
    path('teamdetail/<int:id>/', views.teamdetail, name = "teamdetail"),
    path('postcreate/', views.postcreate, name = "postcreate"),

    path('info_turnBack/', views.info_turnBack, name = "info_turnBack"),
]

gayeong/Match_up/teampage/models.py
from django.db import models
from django.conf import settings
from account.models import *
from community.models import *




class Game_Result(models.Model):
    winner = models.CharField(max_length = 15, null = True)
    coner = models.PositiveIntegerField(default = 0)
    penalty = models.PositiveIntegerField(default = 0)
    offside = models.PositiveIntegerField(default = 0)
    warn = models.PositiveIntegerField(default = 0)
    late = models.BooleanField(default = False )
    foul = models.PositiveIntegerField(default = 0)


class Game(models.Model):
    team_right = models.CharField(max_length=15)
    team_left = models.CharField(max_length=15)
    place = models.CharField(max_length = 25, null = True)
    date = models.DateTimeField(auto_now=True)
    finish = models.BooleanField(default = False)
    results = models.ForeignKey(Game_Result, on_delete = models.PROTECT)


#python manage.py makemigrations


class Team_Post(TimeDate):
    ZeroOrOne = [
        ('일반', '일반'),
        ('공지사항', '공지사항'),
    ]

    team_name = models.ForeignKey(Team, on_delete = models.CASCADE)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE) # 작성자
    title = models.CharField(max_length=200)
    title_image = models.ImageField(upload_to = 'image', blank=True)
    content = models.TextField()
    importent = models.CharField(max_length=10, choices=ZeroOrOne)
    

    def __str__(self):
        return self.title

    #1번 글의 경우 -> post/1
    def get_absolute_urls(self):
        return reverse("team", args=[str(self.id)]).py

    def is_title_more11s(self):
        return len(self.title) > 11
    
    def get_title_under11s(self):
        return self.title[:11]
 

gayeong/Match_up/teampage/forms.py
from django import forms
from .models import *
from django.forms.widgets import ClearableFileInput

class Team_Post_Form(forms.ModelForm):
    class Meta:
        model = Team_Post
        fields = ('title', 'title_image', 'content', 'importent')
        labels = {
            'title': '',
            'title_image': '',
            'content': '',
            'importent': '',
        }
        

gayeong/Match_up/teampage/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import auth
from account.models import *
from .models import *
from .forms import *
from account.forms import *

# Create your views here.
def teaminfo(request):
    error = ""
    try:
            
        my_profile = Profile.objects.get(user__username=request.user)
        teamname = my_profile.teams
        print(teamname.all().count())
        if teamname.all().count() == 0: 
            print("팀 없음")
        else:
            tes = my_profile.teams.all()
            print(tes)

        print(my_profile)
    except:
        error = "로그인하지 않았습니다."
        my_profile = ""
        tes = ""

    context = {
        "my_profile" : my_profile,
        "error" : error,
        "tes" : tes,
    }

    return render(request, 'teaminfo.html', context)

def management(request):
    return render(request, 'management.html')

def testpage(request):
    return render(reqeust, 'testpage.html')

def simulation(request):
    return render(request, 'simulation.html')

def team_list(request):
    team_list = Team.objects.all()
    context = {
        "team_list" : team_list
    }
    return render(request, 'team_list.html', context)

def team_create(request):
    if request.method == "POST":
        tform = TeamForm(request.POST)
        if tform.is_valid():
            creater = Profile.objects.get(user__username=request.user)
            
            team_form = tform.save(commit=False)
            team_form.king = creater
            team_form.personnel = team_form.personnel+1
            team_form.intro = request.POST.get("intro")
            team_form.phone = creater.phone
            team_form.save()
            
            named = Team.objects.get(team_name = team_form.team_name)
            creater.teams.add(named)
            creater.save() 
            
            return redirect('/teaminfo')

    else:
        team_list = Team.objects.all()
        tform = TeamForm()
        context = {
            "team_list" : team_list,
            "tform" : tform,
        }
        return render(request, 'team_create.html', context)

def info_turnBack(request):
    return redirect('/teaminfo')

def teamdetail(request, id):
    username = request.user.username
    us1 = Profile.objects.get(user__username=request.user)
    user_team = us1.teams
    tea = Team.objects.get(pk = id)

    context = {
        "tea":tea,
        "user_team": user_team,
    }
    
    return render(request, 'teamdetail.html', context)

def postcreate(reqeust):
    return render(request, 'teamcreate.html')

gayeong/Match_up/teampage/templates/team_create.html
{% extends 'base.html' %}


{% block title %}Team_Create{% endblock %}

{% load static %}


{% block sty %} 
    <style>
        img {
            vertical-align: middle;
            border-style: none;
        }
        .led {
            width: 100%;
            margin: 30px auto; 
            background: #efefef; 
            text-align: center; 
            color: rgb(63, 63, 63); 
            font-family: sans-serif; 
            transition: ease .3s;
        }
        form{
            width: 100%;
            text-align: center;
            margin: 30px auto; 
        }
        
    </style>
{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <div class = "led">
            <h3>팀 생성</h3>
        </div>

        <div style = "padding-left: 3%;">
            <h2><a class="btn btn-outline-secondary" href="{% url 'teampage:info_turnBack'%}">뒤로가기</a> </h2>
        </div>

        <form action = "" method="POST">
            {% csrf_token %}

                <div class="row">
                    <div class="col-lg-5">
                        <p>팀 명</p>
                        <p>{{tform.team_name}}</p>

                        <p>팀 이미지</p>
                        <p>{{tform.team_image}}</p>

                        <p>팀 주 활동지역</p>
                        <p>{{tform.region}}</p>

                        <p>팀 소개</p>
                        <input name = "intro" type = "text" placeholder = "팀을 소개해주세요">

                        <p></p>
                        <input class="btn btn-primary" type = "submit" value = "팀 생성">
                    </div>
                </div>

        </form>
    {% else %}
        <div class = "led">
            <h3>로그인 후 진행해주세요</h3>
        </div>
    
        
    {% endif %}


{% endblock %}

gayeong/Match_up/teampage/templates/team_list.html
{% extends 'base.html' %}


{% block title %}teampage{% endblock %}

{% load static %}


{% block sty %} 
    <style>
        img {
            vertical-align: middle;
            border-style: none;
        }
        .marketing .col-lg-5 {
            margin-top: 1rem;
            margin-bottom: 1rem;
            text-align: center;
        }
        #for-padding-yes{
            line-height: 50px;
        }
        #for-padding-yes p{
            margin-top: 0.5rem;
            margin-bottom: 1rem;
            text-align: center;
            vertical-align: middle;
        }
        #not-have-team{
            margin-top: 3%;
            margin-left: 30%;
            margin-right:30%;
            text-align: center;
        }
        #team-button{
            font-size: large;
            margin:1%
        } 
    </style>
{% endblock %}

{% block content %}
    <div style = "padding-left: 3%;">
        <h2><a class="btn btn-outline-secondary"  href="{% url 'teampage:info_turnBack'%}">뒤로가기</a> </h2>
    </div>
    {% for team in team_list %}
        
        <div class="container marketing">

            <!-- Three columns of text below the carousel -->
            <div class="row">
            <div class="col-lg-5">
                <p></p>
                <img class="rounded-rectangle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
                <h2><span class="badge badge-pill badge-info">{{team.team_name}}</span></h2>
                <p>{{team.region}}</p>
            
            </div><!-- /.col-lg-4 -->
            <div class="col-lg-5" id = "for-padding-yes">
                <p style = "vertical-align: middle;">{{team.intro}}</p>
                <a href = "{% url 'teampage:teamdetail' team.id %}" class="btn btn-outline-secondary">버튼</a>
            </div><!-- /.col-lg-4 -->
                
            </div><!-- /.row -->


            <!-- START THE FEATURETTES -->

            <hr class="featurette-divider">



        </div>
    {% endfor %}

{% endblock %}

gayeong/Match_up/teampage/templates/teamdetail.html
{% extends 'base.html' %}


{% block title %}Teaminfo{% endblock %}

{% load static %}


{% block sty %} 
    <style>
        td{
            width: 50px;
            height: 50px;
            text-align: center;
            font-size: 20px;
            font-family: 굴림;
            border:2px;
            border-color : #3333FF;
            border-radius: 8px;
        }

        img {
            vertical-align: middle;
            border-style: none;
        }
        .marketing .col-lg-5 {
            text-align: center;
        }
        #for-padding-yes{
            line-height: 50px;
        }
        #for-padding-yes p{
            margin-bottom: 0.7rem;
            text-align: center;
            vertical-align: middle;
        }
        #not-have-team{
            margin-top: 3%;
            margin-left: 30%;
            margin-right:30%;
            text-align: center;
        }
        #team-button{
            font-size: large;
            margin:1%
        }
        .led {
            width: 80%;
            margin: 30px auto; 
            background: #efefef; 
            text-align: center; 
            color: rgb(63, 63, 63); 
            font-family: sans-serif; 
            transition: ease .3s;
        }
    </style>
    <style>
        body {
        font-family: Tahoma;
        }
        header {
        text-align: center;
        }
        #calendar {
        width: 100%;
        }
        #calendar a {
        color: #8e352e;
        text-decoration: none;
        }
        #calendar ul {
        list-style: none;
        padding: 0;
        margin: 0;
        width: 100%;
        }
        #calendar li {
        display: block;
        float: left;
        width: 14.342%;
        padding: 5px;
        box-sizing: border-box;
        border: 1px solid #ccc;
        margin-right: -1px;
        margin-bottom: -1px;
        }
        #calendar ul.weekdays {
        height: 40px;
        background: #8e352e;
        }
        #calendar ul.weekdays li {
        text-align: center;
        text-transform: uppercase;
        line-height: 20px;
        border: none !important;
        padding: 10px 6px;
        color: #fff;
        font-size: 13px;
        }
        #calendar .days li {
        height: 180px;
        }
        #calendar .days li:hover {
        background: #d3d3d3;
        }
        #calendar .date {
        text-align: center;
        margin-bottom: 5px;
        padding: 4px;
        background: #333;
        color: #fff;
        width: 20px;
        border-radius: 50%;
        float: right;
        }
        #calendar .event {
        clear: both;
        display: block;
        font-size: 13px;
        border-radius: 4px;
        padding: 5px;
        margin-top: 40px;
        margin-bottom: 5px;
        line-height: 14px;
        background: #e4f2f2;
        border: 1px solid #b5dbdc;
        color: #009aaf;
        text-decoration: none;
        }
        #calendar .event-desc {
        color: #666;
        margin: 3px 0 7px 0;
        text-decoration: none;
        }
        #calendar .other-month {
        background: #f5f5f5;
        color: #666;
        }
        @media (max-width: 768px) {
            #calendar .weekdays, #calendar .other-month {
                display: none;
            }
            #calendar li {
                height: auto !important;
                border: 1px solid #ededed;
                width: 100%;
                padding: 10px;
                margin-bottom: -1px;
            }
            #calendar .date {
                float: none;
            }
        }
    </style>

<script type="text/javascript">
    var today = new Date();//오늘 날짜//내 컴퓨터 로컬을 기준으로 today에 Date 객체를 넣어줌
    var date = new Date();//today의 Date를 세어주는 역할
    function prevCalendar() {//이전 달
    // 이전 달을 today에 값을 저장하고 달력에 today를 넣어줌
    //today.getFullYear() 현재 년도//today.getMonth() 월  //today.getDate() 일 
    //getMonth()는 현재 달을 받아 오므로 이전달을 출력하려면 -1을 해줘야함
     today = new Date(today.getFullYear(), today.getMonth() - 1, today.getDate());
     buildCalendar(); //달력 cell 만들어 출력 
    }

    function nextCalendar() {//다음 달
        // 다음 달을 today에 값을 저장하고 달력에 today 넣어줌
        //today.getFullYear() 현재 년도//today.getMonth() 월  //today.getDate() 일 
        //getMonth()는 현재 달을 받아 오므로 다음달을 출력하려면 +1을 해줘야함
         today = new Date(today.getFullYear(), today.getMonth() + 1, today.getDate());
         buildCalendar();//달력 cell 만들어 출력
    }
    function buildCalendar(){//현재 달 달력 만들기
        var doMonth = new Date(today.getFullYear(),today.getMonth(),1);
        //이번 달의 첫째 날,
        //new를 쓰는 이유 : new를 쓰면 이번달의 로컬 월을 정확하게 받아온다.     
        //new를 쓰지 않았을때 이번달을 받아오려면 +1을 해줘야한다. 
        //왜냐면 getMonth()는 0~11을 반환하기 때문
        var lastDate = new Date(today.getFullYear(),today.getMonth()+1,0);
        //이번 달의 마지막 날
        //new를 써주면 정확한 월을 가져옴, getMonth()+1을 해주면 다음달로 넘어가는데
        //day를 1부터 시작하는게 아니라 0부터 시작하기 때문에 
        //대로 된 다음달 시작일(1일)은 못가져오고 1 전인 0, 즉 전달 마지막일 을 가져오게 된다
        var tbCalendar = document.getElementById("calendar");
        //날짜를 찍을 테이블 변수 만듬, 일 까지 다 찍힘
        var tbCalendarYM = document.getElementById("tbCalendarYM");
        //테이블에 정확한 날짜 찍는 변수
        //innerHTML : js 언어를 HTML의 권장 표준 언어로 바꾼다
        //new를 찍지 않아서 month는 +1을 더해줘야 한다. 
         tbCalendarYM.innerHTML = today.getFullYear() + "년 " + (today.getMonth() + 1) + "월"; 

         /*while은 이번달이 끝나면 다음달로 넘겨주는 역할*/
        while (tbCalendar.rows.length > 2) {
        //열을 지워줌
        //기본 열 크기는 body 부분에서 2로 고정되어 있다.
              tbCalendar.deleteRow(tbCalendar.rows.length-1);
              //테이블의 tr 갯수 만큼의 열 묶음은 -1칸 해줘야지 
            //30일 이후로 담을달에 순서대로 열이 계속 이어진다.
         }
         var row = null;
         row = tbCalendar.insertRow();
         //테이블에 새로운 열 삽입//즉, 초기화
         var cnt = 0;// count, 셀의 갯수를 세어주는 역할
        // 1일이 시작되는 칸을 맞추어 줌
         for (i=0; i<doMonth.getDay(); i++) {
         /*이번달의 day만큼 돌림*/
              cell = row.insertCell();//열 한칸한칸 계속 만들어주는 역할
              cnt = cnt + 1;//열의 갯수를 계속 다음으로 위치하게 해주는 역할
         }
        /*달력 출력*/
         for (i=1; i<=lastDate.getDate(); i++) { 
         //1일부터 마지막 일까지 돌림
              cell = row.insertCell();//열 한칸한칸 계속 만들어주는 역할
              cell.innerHTML = i;//셀을 1부터 마지막 day까지 HTML 문법에 넣어줌
              cnt = cnt + 1;//열의 갯수를 계속 다음으로 위치하게 해주는 역할
          if (cnt % 7 == 1) {/*일요일 계산*/
              //1주일이 7일 이므로 일요일 구하기
              //월화수목금토일을 7로 나눴을때 나머지가 1이면 cnt가 1번째에 위치함을 의미한다
            cell.innerHTML = "<font color=#F79DC2>" + i
            //1번째의 cell에만 색칠
        }    
          if (cnt%7 == 0){/* 1주일이 7일 이므로 토요일 구하기*/
              //월화수목금토일을 7로 나눴을때 나머지가 0이면 cnt가 7번째에 위치함을 의미한다
              cell.innerHTML = "<font color=skyblue>" + i
              //7번째의 cell에만 색칠
               row = calendar.insertRow();
               //토요일 다음에 올 셀을 추가
          }
          /*오늘의 날짜에 노란색 칠하기*/
          if (today.getFullYear() == date.getFullYear()
             && today.getMonth() == date.getMonth()
             && i == date.getDate()) {
              //달력에 있는 년,달과 내 컴퓨터의 로컬 년,달이 같고, 일이 오늘의 일과 같으면
            cell.bgColor = "#FAF58C";//셀의 배경색을 노랑으로 
           }
         }
    }
</script>
{% endblock %}

{% block content %}
    <div class="container marketing">

        <!-- Three columns of text below the carousel -->
        <div class="row">
            <div class="col-lg-5">
                <p></p>
                <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
                <p style="font-size: x-large; font-weight: bold;">대표자 : {{tea.king}}</p>
                <h2><span class="badge badge-pill badge-info">{{tea.team_name}}</span></h2>
            
            </div><!-- /.col-lg-4 -->
            <div class="col-lg-5" id = "for-padding-yes">
                <p>소개 : {{tea.intro}}</p>
                <p>현재 인원 : {{tea.personnel}}</p>
                <p>주 활동 지역 : {{tea.region}}</p>
                <p>대표 전화번호 : {{tea.phone}} 010-2222-2222</p>
            </div><!-- /.col-lg-4 -->
            
        </div>

        <hr class="featurette-divider"> <!--여기부터 팀 게시판 -->


    {% for my in user_team.all %}
        {% if my.team_name == tea.team_name %}
        <a class="btn btn-primary" href="{% url 'teampage:postcreate' %}" role="button" style = "float: right; margin-top: 0.3rem; margin-bottom:1rem;">글쓰기</a>
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">작성자</th>
                    <th scope="col">제목</th>
                    <th scope="col">작성 날짜</th>
                </tr>
                </thead>
                <tbody>
                {% for p in post %}
                    <tr>
                    <th scope="row">{{p.id}}</th>
                    <td>{{p.author.user_name}}</td>
                    <td><a href = "{% url 'community:postDetail' p.id %}">{{p.title}}</a></td>
                    <td>{{p.created_at}}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        {% else %}
            <div class = "led">
                <h3>{{error}}</h3>
            </div>
        {% endif %}
    {% endfor %}
          <hr class="featurette-divider"> <!--여기부터 달력-->

          <table id="calendar" style="border-color:#3333FF; text-align: center;">
            <tr><!-- label은 마우스로 클릭을 편하게 해줌 -->
                <td><label onclick="prevCalendar()"></label></td>
                <td text-align="center" id="tbCalendarYM" colspan="5">
                yyyy년 m월</td>
                <td><label onclick="nextCalendar()">>
                    
                </label></td>
            </tr>
            <tr>
                <td text-align="center" style = "color:rgb(255, 95, 95)">일</td>
                <td text-align="center">월</td>
                <td text-align="center">화</td>
                <td text-align="center">수</td>
                <td text-align="center">목</td>
                <td text-align="center">금</td>
                <td text-align="center" style = "color:rgb(95, 151, 255)">토</td>
            </tr> 
        </table>
        <script language="javascript" type="text/javascript">
            buildCalendar();//
        </script>


    </div>
{% endblock %}

gayeong/Match_up/teampage/templates/teaminfo.html
{% extends 'base.html' %}


{% block title %}Teaminfo{% endblock %}

{% load static %}


{% block sty %} 
    <style>
        #maner{
            text-align: center;
            margin-top: 3%;
            margin-left: 70%;
        }
        img {
            vertical-align: middle;
            border-style: none;
        }
        .marketing .col-lg-5 {
            margin-top: 0.5rem;
            margin-bottom: 0.5rem;
            text-align: center;
        }
        #for-padding-yes{
            line-height: 50px;
        }
        #for-padding-yes p{
            margin-top: 1.5rem;
            margin-bottom: 1rem;
            text-align: center;
            vertical-align: middle;
        }
        #not-have-team{
            margin-top: 3%;
            margin-left: 30%;
            margin-right:30%;
            text-align: center;
        }
        #team-button{
            font-size: large;
            margin:1%
        } 
    </style>
{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        {% if my_profile.teas_valid %}
            <div id = "not-have-team">
                <p style = "font-size: larger; font-weight: bold;">팀에 들어가세요</p>
                <a href="{% url 'teampage:team_create' %}" id = "team-button" class="badge badge-primary">팀 생성하기</a>
                <a href="{% url 'teampage:team_list' %}" id = "team-button" class="badge badge-secondary">팀 찾아보기</a>
                
            </div>
        {% else %}
            <div class = "led">
                <h3 style = "color:font-weight: bold;">Your Team</h3>
            </div>
        {% for i in tes %}
            <div class="container marketing">

                <!-- Three columns of text below the carousel -->
                <div class="row">
                    <div class="col-lg-5">
                        <p></p>
                        <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
                        <h2><span class="badge badge-pill badge-info">{{i.team_name}}</span></h2>
                    
                    </div><!-- /.col-lg-4 -->
                    <div class="col-lg-5" id = "for-padding-yes">
                        <p>{{i.intro}}</p>
                        <a href = "{% url 'teampage:teamdetail' i.id %}" class="btn btn-outline-secondary">자세히 보기</a>
                    </div><!-- /.col-lg-4 -->
                    
                </div>
                <hr class="featurette-divider">

            </div>
        {% endfor %}
            <div class="row">
                <div class="col-lg-5">
                    <a href = "{% url 'teampage:team_list' %}" class="btn btn-outline-primary" id = "maner"> 팀 전체보기 </a>
                </div>
            </div>
        {% endif %}
    {% else %}
        <div class = "led">
            <h3 style = "color: rgb(253, 80, 80); font-weight: bold;">로그인 후 이용해주세요</h3>

        </div>
    {% endif %}

{% endblock %}