gayeong/Match_up/Match_up/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls', namespace = "account")),
    path('', include('community.urls', namespace = "community")),
    path('', include('teampage.urls', namespace = "teampage")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gayeong/Match_up/account/urls.py
from django.contrib import admin
from django.urls import path, include 

from.import views

app_name = "account"

urlpatterns = [
    path('', views.main, name = 'main'),
    path('log_in/', views.log_in, name = "log_in"),
    path('log_out/', views.log_out, name = "log_out"),
    path('sign_up/', views.sign_up, name = "sign_up"),
    path('my_page/', views.my_page, name = "my_page"),
]

gayeong/Match_up/community/urls.py
from django.contrib import admin
from django.urls import path, include 

from.import views

app_name = "community"

urlpatterns = [
    path('free_board/', views.free_board, name = 'free_board'),
    path('review_board/', views.review_board, name = "review_board"),
    path('hire_board/', views.hire_board, name = "hire_board"),
    path('createPost_free/', views.createPost_free, name = "createPost_free"),
    path('createPost_review/', views.createPost_review, name = "createPost_review"),
    path('createPost_hire/', views.createPost_hire, name = "createPost_hire"),
    
    path('turnBack/<int:id>/', views.turnBack, name = "turnBack"),
    path('postDetail/<int:id>/', views.postDetail, name = "postDetail"),
    path('postDelete/<int:id>/', views.postDelete, name = "postDelete"),
    path('postEdit/<int:id>/', views.postEdit, name = "postEdit"),

    #path('turnBack/', views.turnBack, name = "turnBack"),
]

gayeong/Match_up/teampage/urls.py
from django.contrib import admin
from django.urls import path, include 

from.import views

app_name = "teampage"

urlpatterns = [
    path('management/', views.management, name = 'management'),
    path('teaminfo/', views.teaminfo, name = "teaminfo"),
    path('testpage/', views.testpage, name = "testpage"),
    path('simulation/', views.simulation, name = "simulation"),
    path('team_list/', views.team_list, name = "team_list"),
    path('team_create/', views.team_create, name = "team_create"),
    path('teamdetail/<int:id>/', views.teamdetail, name = "teamdetail"),
    path('postcreate/', views.postcreate, name = "postcreate"),

    path('info_turnBack/', views.info_turnBack, name = "info_turnBack"),
]

gayeong/Match_up/Match_up/templates/share/_navbar.html
{% if user.is_authenticated %}



<nav >
  <div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-3"></div>
    <div class="col-sm-3"></div>
    <nav>
      <!-- <span class="badge badge-pill badge-info" style="font-size: medium; margin-right: 0.4cm;"> username : {{user.Profile.user_name}} </span> -->
      <button class ="btn btn-warning" type="button"><a class = "btn" href="{% url 'account:log_out' %}">로그아웃</a></button>
      <span>&nbsp;</span>
      <button class="btn btn-info" type="button"><a  class="btn" href = "{% url 'account:my_page' %}">마이페이지</a></button>
      <span>    </span>
    </nav>
    </div>
  </div>
</nav>

{% else %}

<nav>
    <div class="row">
      <div class="col-sm-3"></div>
      <div class="col-sm-3"></div>
      <div class="col-sm-3"></div>
      <nav>
        <button class ="btn btn-warning" type="button"><a class = "btn" href="{% url 'account:log_in' %}">로그인</a></button>
        <span>&nbsp;</span>
        <button class="btn btn-info" type="button"><a  class="btn" href = "{% url 'account:sign_up' %}">회원가입</a></button>
      </nav>
      </div>
    </div>
  </nav>
  {% endif %}





  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'account:main' %}" style="color: rgb(95, 151, 255); font-size: large; font-weight: bold;">Match Up</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
  
  
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'account:main' %}">Home <span class="sr-only">(current)</span></a>
          </li>
  
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              커뮤니티
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{% url 'community:free_board' %}">자유게시판</a>
              <a class="dropdown-item" href="{% url 'community:review_board' %}">경기 후기</a>
              <a class="dropdown-item" href="{% url 'community:hire_board' %}">용병 모집</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              팀
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{% url 'teampage:teaminfo' %}">팀 정보</a>
              <a class="dropdown-item" href="{% url 'teampage:simulation' %}">시뮬레이션</a>
              <a class="dropdown-item" href="{% url 'teampage:management' %}">팀 관리</a>
              <a class="dropdown-item" href="{% url 'teampage:management' %}">팀 생성(테스트)</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              팀 매칭
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">실시간 매칭</a>
              <a class="dropdown-item" href="#">자동 매칭</a>
            </div>
          </li>
  
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              경기장 예약
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">홈 경기장</a>
              <a class="dropdown-item" href="#">어웨이 경기장</a>
            </div>
          </li>
  
        </ul>
      </div>
    </nav>
  